-- Feste, versionierte Taxonomie. Freie LLM-Tags driften nach 200 Rezepten
-- auseinander (Nachtisch / Dessert / Suessspeise) und machen die Suche unbrauchbar.
insert into public.tags (axis, slug, label_de, sort_order) values
  ('course','vorspeise','Vorspeise',1),
  ('course','hauptgericht','Hauptgericht',2),
  ('course','beilage','Beilage',3),
  ('course','dessert','Dessert',4),
  ('course','fruehstueck','Fruehstueck',5),
  ('course','snack','Snack',6),
  ('course','gebaeck','Gebaeck',7),
  ('course','getraenk','Getraenk',8),
  ('course','sauce_fond','Sauce und Fond',9),
  ('course','suppe','Suppe',10),
  ('course','salat','Salat',11),

  ('main_ingredient','rind','Rind',1),
  ('main_ingredient','schwein','Schwein',2),
  ('main_ingredient','kalb','Kalb',3),
  ('main_ingredient','lamm','Lamm',4),
  ('main_ingredient','gefluegel','Gefluegel',5),
  ('main_ingredient','wild','Wild',6),
  ('main_ingredient','fisch','Fisch',7),
  ('main_ingredient','meeresfruechte','Meeresfruechte',8),
  ('main_ingredient','nudeln','Nudeln',9),
  ('main_ingredient','reis','Reis',10),
  ('main_ingredient','kartoffel','Kartoffel',11),
  ('main_ingredient','huelsenfruechte','Huelsenfruechte',12),
  ('main_ingredient','gemuese','Gemuese',13),
  ('main_ingredient','pilze','Pilze',14),
  ('main_ingredient','ei','Ei',15),
  ('main_ingredient','kaese','Kaese',16),
  ('main_ingredient','obst','Obst',17),
  ('main_ingredient','getreide','Getreide',18),
  ('main_ingredient','tofu_soja','Tofu und Soja',19),

  ('cuisine','deutsch','Deutsch',1),
  ('cuisine','oesterreichisch','Oesterreichisch',2),
  ('cuisine','schweizerisch','Schweizerisch',3),
  ('cuisine','italienisch','Italienisch',4),
  ('cuisine','franzoesisch','Franzoesisch',5),
  ('cuisine','spanisch','Spanisch',6),
  ('cuisine','griechisch','Griechisch',7),
  ('cuisine','tuerkisch','Tuerkisch',8),
  ('cuisine','orientalisch','Orientalisch',9),
  ('cuisine','asiatisch','Asiatisch',10),
  ('cuisine','indisch','Indisch',11),
  ('cuisine','amerikanisch','Amerikanisch',12),
  ('cuisine','lateinamerikanisch','Lateinamerikanisch',13),

  ('diet','vegetarisch','Vegetarisch',1),
  ('diet','vegan','Vegan',2),
  ('diet','glutenfrei','Glutenfrei',3),
  ('diet','laktosefrei','Laktosefrei',4),
  ('diet','low_carb','Low Carb',5),
  ('diet','eiweissreich','Eiweissreich',6),

  ('method','backen','Backen',1),
  ('method','braten','Braten',2),
  ('method','kochen','Kochen',3),
  ('method','duensten','Duensten',4),
  ('method','daempfen','Daempfen',5),
  ('method','schmoren','Schmoren',6),
  ('method','frittieren','Frittieren',7),
  ('method','grillen','Grillen',8),
  ('method','pochieren','Pochieren',9),
  ('method','sous_vide','Sous-vide',10),
  ('method','roh','Roh',11),
  ('method','gratinieren','Gratinieren',12),

  ('occasion','alltag','Alltag',1),
  ('occasion','schnell','Schnell',2),
  ('occasion','meal_prep','Meal Prep',3),
  ('occasion','gaeste','Fuer Gaeste',4),
  ('occasion','festtag','Festtag',5),
  ('occasion','kinder','Fuer Kinder',6),
  ('occasion','ausbildung','Ausbildung',7),

  ('season','fruehling','Fruehling',1),
  ('season','sommer','Sommer',2),
  ('season','herbst','Herbst',3),
  ('season','winter','Winter',4),
  ('season','ganzjaehrig','Ganzjaehrig',5)
on conflict (axis, slug) do nothing;
